using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace projecte_sensor
{
    class Program
    { 
        static void Main(string[] args)
        {
            int n1;
            string n = Console.ReadLine();
            n1 = Convert.ToInt32(n);
            contro c = new contro();
            c.control(n1);
            Console.ReadLine();
        }
    }
   class senor
    {
        int p=0;
         public int sensor1()
        {
           // Console.ReadLine();
            if ( p < 20)
            {
                contro c = new contro();
                c.control(p);
            }

            
            return 0;
        }
    }
    class contro
    {
        
        public  bool  control(int y)
        {
            if (y < 20)
            {

                lamp.lamp1(true);
                return true;
            }
            else if (y >= 20)
                Console.WriteLine("  light  is internale   ");
                return false;
        }
    }
    class lamp
    {
      static   public void  lamp1(bool  y)
        {
            if (y)
            {
                Console.WriteLine("        light  is  on   ");
            }
            else
                Console.WriteLine("    light  is normal  ");


        }
    }
}

